# Generated by Django 2.0.6 on 2018-06-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pylightcommon', '0002_load_fixtures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectedsystem',
            name='lastIP',
            field=models.GenericIPAddressField(verbose_name='Last known IP address of Connection'),
        ),
        migrations.AlterField(
            model_name='connectedsystem',
            name='lastMacAddress',
            field=models.CharField(max_length=255, verbose_name='Mac Address of Connection'),
        ),
        migrations.AlterField(
            model_name='connectedsystem',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name of Connection'),
        ),
    ]
