# Generated by Django 2.0.6 on 2018-06-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pylightcommon', '0003_auto_20180616_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsettings',
            name='connectedToServer',
            field=models.BooleanField(default=False, verbose_name='Flag for connected to server'),
        ),
    ]
