# Generated by Django 2.0.6 on 2018-06-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pylightcommon', '0004_clientsettings_connectedtoserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsettings',
            name='searching',
            field=models.BooleanField(default=False, verbose_name='Searching flag for client'),
        ),
    ]
